"""empty message

Revision ID: 6e0e3c1d93c3
Revises: 912bbe5e6f31
Create Date: 2025-07-09 23:51:13.344226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0e3c1d93c3'
down_revision = '912bbe5e6f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_people',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_people')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_people')
    # ### end Alembic commands ###
