"""empty message

Revision ID: 912bbe5e6f31
Revises: 4a4e30ca9cb8
Create Date: 2025-07-09 23:49:00.422695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912bbe5e6f31'
down_revision = '4a4e30ca9cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('gravity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planet',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_planet')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('favorite_planet')
    op.drop_table('planet')
    # ### end Alembic commands ###
